linters:
  stylelint:
    config: 'stylelint.config.js'
    
    files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'
        - 'SASS/0-base/_base-dir.scss*'
fixers:
    enable: true